general {
    hide_cursor = false
    grace = 0
}

background {
    monitor = 
    path = ~/Documentos/dotfiles/wallpapers/mr-robot.jpg
    blur_passes = 2
    blur_size = 1
}

############################
# RELÓGIO
############################

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = SF Pro Text Bold
    font_size = 112
    color = rgba(255, 104, 123, 1)
    position = 75, 60
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%d/%m/%Y"
    font_family = SF Pro Text Bold
    font_size = 22
    color = rgba(255, 104, 123, 1)
    position = 195, -42
    halign = left
    valign = center
}

############################
# USUÁRIO
############################

# label {
#     monitor =
#     text = $USER
#     font_family = SF Pro Text
#     font_size = 16
#     color = rgb(FB,F1,C7)
#     position = 80, -40
#     halign = left
#     valign = center
# }

############################
# PASSWORD
############################

input-field {
    monitor =
    size = 225, 36
    position = 170, -140
    halign = left
    valign = center
    outline_thickness = 2

    rounding = 5
    outer_color = rgba(255, 104, 123, 1)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(255, 104, 123, 1)

    font_family = SF Pro Text
    placeholder_text = Digite sua senha
    dots_size = 0.25
    dots_spacing = 0.4
    fade_on_empty = true
}

############################
# AVISO
############################

# label {
#     monitor =
#     text = $FAIL
#     font_family = SF Pro Text
#     font_size = 12
#     color = rgb(FB,F1,C7)
#     position = 80, 70
#     halign = left
#     valign = center
# }

############################
# BOTÕES (VISUAIS)
############################

# label {
#     monitor =
#     text = ⏻  Reboot (Ctrl+R)   ⏼  Poweroff (Ctrl+P)
#     font_family = SF Pro Text
#     font_size = 12
#     color = rgb(FB,F1,C7)
#     position = 80, 130
#     halign = left
#     valign = center
# }
