# Cursor Wayland (Hyprcursor)
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,18

# Cursor XWayland / GTK
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,18

# Desktop/session info
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# GTK backend
env = GDK_BACKEND,wayland,x11,*

# Qt
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_STYLE_OVERRIDE,kvantum

# GTK / Libadwaita
env = GTK_APPLICATION_PREFER_DARK_THEME,1
env = GTK_APPEARANCE_PREFERENCE,dark
